/*
Copyright 2022 Adobe. All rights reserved.
This file is licensed to you under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License. You may obtain a copy
of the License at http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
OF ANY KIND, either express or implied. See the License for the specific language
governing permissions and limitations under the License.
*/

/**
 * Registry module for the adobe-developer-skills MCP server.
 *
 * Loads registry.json (generated by scripts/generate-registry.js at prebuild/pretest)
 * and builds the catalog and resourceCache at module scope.
 */

'use strict'

const registryData = require('./registry.json')

const { deployId, skills } = registryData

/**
 * Catalog: name + description only, for list_skills
 */
const catalog = skills.map(({ name, description }) => ({ name, description }))

/**
 * Registry: full skill data (name, description, body, folder, references)
 */
const registry = skills.reduce((map, skill) => {
    map[skill.name] = skill
    return map
}, {})

/**
 * resourceCache: Map of "<skill_name>/<ref_path>" → file content string
 * Content is embedded in registry.json at build time by generate-registry.js,
 * so no filesystem access is needed at runtime (works correctly in webpack bundles).
 */
const resourceCache = new Map()

for (const skill of skills) {
    for (const ref of skill.references) {
        const key = `${skill.name}/${ref.path}`
        if (ref.content !== undefined) {
            resourceCache.set(key, ref.content)
        } else {
            console.warn(`Warning: no embedded content for resource ${key}`)
        }
    }
}

module.exports = { deployId, registry, catalog, resourceCache }
